# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhZgxBrVhqCTW4qmYjWKLznhEOQ1gyVH
"""

import pandas as pd
import sqlite3 as sq

df = pd.read_csv('mobile_activity.csv')
print(df.head())

conn = sq.connect('users_data.db')
df1 = pd.read_sql("SELECT * FROM users_activity LIMIT 10", conn)
conn.close()
print(df1)

print(df.info)
print(df.describe)
print(df['country'].value_counts())